from langgraph.graph import StateGraph, START, END
from langgraph.graph.message import add_messages
from typing import Annotated, TypedDict

from langchain_core.messages import HumanMessage, SystemMessage
from langchain_core.tools import BaseTool

from langgraph.prebuilt import ToolNode

from app.core.llm import llm
from app.prompts.system_prompt import SYSTEM_PROMPT
from app.services.retrieval import retrieve_context
from app.tools.file_tools import read_file


tools = [read_file]

llm_with_tools = llm.bind_tools(tools)

class AgentState(TypedDict):
    messages: Annotated[list, add_messages]


def assistant_node(state: AgentState) -> str:
    """
    A node that represents the assistant's response in the conversation.

    Args:
        state (AgentState): The current state of the conversation, including messages.

    Returns:
        str: The assistant's response generated by the LLM.
    """
    messages = state["messages"]

    last_user_message = messages[-1].content

    retrieved_context = retrieve_context(last_user_message)

    system_message = SystemMessage(
        content=f"""
        {SYSTEM_PROMPT}

        RETRIEVED CODEBASE CONTEXT:
        {retrieved_context}
        """
    )

    response = llm_with_tools.invoke(
        [system_message] + messages
    )

    return {
        "messages": [response]
    }

tool_node = ToolNode(tools)

def route_tools(state: AgentState):
    last_message = state["messages"][-1]

    if last_message.tool_calls:
        return "tools"

    return END

graph_builder = StateGraph(AgentState)

graph_builder.add_node("assistant", assistant_node)
graph_builder.add_node("tools", tool_node)

graph_builder.add_edge(START, "assistant")

graph_builder.add_conditional_edges("assistant", route_tools)

graph_builder.add_edge("tools", "assistant")

graph = graph_builder.compile()